DROP TABLE IF EXISTS banktest.bank CASCADE;
DROP TABLE IF EXISTS banktest.account CASCADE;
DROP TABLE IF EXISTS banktest.movement CASCADE;
DROP TABLE IF EXISTS banktest.customer CASCADE;
DROP SCHEMA IF EXISTS banktest CASCADE;